// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Ql_5DKiToNzsUTx2xcGc2p2jkVpU0WM',
    appId: '1:456762065480:web:690fb43d4fc37bd5cc8e7d',
    messagingSenderId: '456762065480',
    projectId: 'chool-management-428c8',
    authDomain: 'chool-management-428c8.firebaseapp.com',
    storageBucket: 'chool-management-428c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBWS3wSPzVWkEppGKzM0Awa_HblhQVPQ',
    appId: '1:456762065480:android:c0c4806a97730f27cc8e7d',
    messagingSenderId: '456762065480',
    projectId: 'chool-management-428c8',
    storageBucket: 'chool-management-428c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tUsr1D9g2jMXOsJLJ53x-g5b5CwIJGQ',
    appId: '1:456762065480:ios:f1920febbfc330ebcc8e7d',
    messagingSenderId: '456762065480',
    projectId: 'chool-management-428c8',
    storageBucket: 'chool-management-428c8.firebasestorage.app',
    iosClientId: '456762065480-qjvitb5hjn04ruar1rvprigiihf9bns0.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolManagement',
  );
}
